# Generated by Django 5.2.1 on 2025-05-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category_type', models.CharField(choices=[('HOT_BEVERAGES', 'Hot Beverages'), ('COLD_BEVERAGES', 'Cold Beverages'), ('SOFT_DRINKS', 'Soft Drinks'), ('FRESH_JUICES', 'Fresh Juices'), ('SNACKS', 'Snacks')], default='HOT_BEVERAGES', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_jwt_test.category')),
            ],
        ),
    ]
